---
- name: Update u1 servers
  hosts: u1
  become: yes

  tasks:
  - name: Install Apache2
    apt: 
      name: apache2
      state: present
  
  - name: start apache2
    service:
     name: apache2
     state: started

  - name: enable apache2
    service:
     name: apache2
     enabled: yes
  
...